# This is a generated file. Not intended for manual editing.
services:
  booklist.api:
    build:
      context: "/Users/izzatmelikov/Desktop/WebAppBookList/App/Backend"
      dockerfile: "BookList.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/BookList.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "booklist.api:dev"
    ports: []
    volumes:
    - "/Users/izzatmelikov/Desktop/WebAppBookList/App/Backend/BookList.Api:/app:rw"
    - "/Users/izzatmelikov/Desktop/WebAppBookList/App/Backend:/src:rw"
    - "/Users/izzatmelikov/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
