services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: BooksDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
        - postgres_data:/var/lib/postgresql/data

  
#  booklist.api:
#    image: booklist.api
#    build:
#      context: .
#      dockerfile: BookList.Api/Dockerfile
#    depends_on:
#      - db
#    ports:
#      - 5100:5101
      
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data: {}